# Generated by Django 4.0.2 on 2022-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=35)),
                ('sec_emp', models.CharField(max_length=3)),
                ('section_name', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_id', models.CharField(max_length=35)),
                ('issue_date', models.DateField()),
                ('username', models.CharField(max_length=30)),
                ('wing', models.CharField(default=None, max_length=35)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=10)),
                ('machine_no', models.CharField(max_length=35)),
                ('U_id', models.CharField(max_length=35)),
                ('specification', models.CharField(max_length=80)),
                ('purchase_data', models.DateField()),
                ('cost', models.IntegerField()),
                ('stock_register', models.IntegerField()),
                ('war_amc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('roomNO', models.IntegerField()),
                ('wing', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(max_length=35)),
            ],
        ),
    ]
