# Generated by Django 4.0.2 on 2022-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='wing',
            field=models.CharField(max_length=35),
        ),
    ]
