# Generated by Django 4.0.2 on 2022-07-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_entry_wing'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='warenty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
